// Motion Components
export {
  FadeIn,
  SlideIn,
  ScaleIn,
  PopIn,
  StaggerList,
  StaggerItem,
  PageTransition,
  FadePresence,
  HoverScale,
  HoverLift,
  Collapse,
  Swipeable,
  Pulse,
  Spinner,
  NotificationBadge,
  LikeButton,
} from './components';

// Motion Presets & Variants
export {
  easings,
  durations,
  transitions,
  fadeIn,
  fadeInOut,
  slideInFromLeft,
  slideInFromRight,
  slideInFromTop,
  slideInFromBottom,
  scaleIn,
  scaleInBounce,
  popIn,
  slideAndScale,
  slideAndFade,
  staggerContainer,
  staggerItem,
  buttonPress,
  hoverLift,
  likeAnimation,
  badgePulse,
  collapse,
  modalBackdrop,
  modalContent,
  drawer,
  pageTransition,
  spinner,
  skeletonPulse,
  swipeableCard,
  createStaggerContainer,
  createSlideVariant,
} from './presets';

// Motion Utilities
export {
  useRespectMotionPreference,
  createAccessibleVariant,
  getAccessibleTransition,
  createStagger,
  getStaggerDelay,
  createViewportAnimation,
  randomDelay,
  createLayoutAnimation,
  createSharedLayout,
  createExitAnimation,
  createHoverAnimation,
  createTapAnimation,
  createFocusAnimation,
  createDragAnimation,
  createParallaxEffect,
  buildMotionProps,
  combineVariants,
  createSkeletonAnimation,
  createNotificationAnimation,
  createModalAnimation,
  createDrawerAnimation,
  isSSR,
  conditionalMotion,
} from './utils';

// Re-export framer-motion for convenience
export { motion, AnimatePresence, LayoutGroup } from 'framer-motion';
export type { Variants, Transition } from 'framer-motion';